services:
  mongo:
    container_name: mongo
    build:
      dockerfile: Dockerfile
    privileged: true
    command: |
      make init
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ATLAS_ROOT}/containers:/var/lib/containers
      - ${ATLAS_ROOT}/cni:/etc/cni
      - ./:/srv
    ports:
      - ${PORT}:${PORT}
